stages:
  - doc
  - build

doxygen:
  stage: doc
  image: ubuntu:latest
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq doxygen graphviz
  script:
    - cd ros2_canopen_core && doxygen
  artifacts:
    paths:
    - ros2_canopen_core/doc_output/
  tags:
   - asprunner


.build:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq git-core
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
  script: .industrial_ci/gitlab.sh
  services: []
  variables:
    ISOLATION: shell
  tags:
    - asprunner

galactic:
  extends: [.build]
  image: ros:galactic

#foxy:
#  extends: [.build]
#  image: ros:foxy

