canopen_master:
  ros__parameters:
    dcf_path: "/home/christoph/ws_ros2/src/ros2_canopen/ros2_canopen_core/resources/pilz.dcf"
    yaml_path: "/home/christoph/ws_ros2/src/ros2_canopen/ros2_canopen_core/resources/pilz.yaml"
    can_interface_name: "can0"