name: Docker Image CI

on:
  push:
    branches: [ "binary-testing" ]
  pull_request:
    branches: [ "binary-testing" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ROS buildfarm
      # You may pin to the exact commit or the version.
      # uses: jspricke/ros-deb-builder-action@b228fee69dc963e2544ec895f3dd7098f9179585
      uses: jspricke/ros-deb-builder-action@v1.0
      with:
        # The ROS distribution codename to compile for.
        ROS_DISTRO: rolling
        # The Debian/Ubuntu distribution codename to compile for.
        DEB_DISTRO: jammy

